/**
 * supabaseStore.ts
 * Toutes les opérations de lecture/écriture vers Supabase (documents + chunks + historique).
 */
import { getSupabaseClient } from './supabaseClient';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface SbDocument {
  document_id: string;
  name: string;
  is_folder: boolean;
  parent_id: string | null;
  size_bytes: number;
  mime_type: string;
  status: 'pending' | 'indexing' | 'indexed' | 'failed';
  chunk_count: number;
  error_message?: string;
  uploaded_by: string;
  uploaded_at: string;
}

export interface SbChunk {
  chunk_id: string;
  document_id: string;
  document_name: string;
  page: number;
  chunk_index: number;
  text: string;
}

// ─── Documents ────────────────────────────────────────────────────────────────

export async function sbUpsertDocument(doc: SbDocument): Promise<boolean> {
  const sb = getSupabaseClient();
  if (!sb) return false;

  const { error } = await sb.from('documents').upsert({
    document_id: doc.document_id,
    name: doc.name,
    is_folder: doc.is_folder,
    parent_id: doc.parent_id ?? null,
    size_bytes: doc.size_bytes,
    mime_type: doc.mime_type,
    status: doc.status,
    chunk_count: doc.chunk_count,
    uploaded_by: doc.uploaded_by,
    uploaded_at: doc.uploaded_at,
  }, { onConflict: 'document_id' });

  if (error) {
    console.error('[Supabase] upsertDocument error:', error.message);
    return false;
  }
  return true;
}


export async function sbGetDocuments(status?: string): Promise<SbDocument[]> {
  const sb = getSupabaseClient();
  if (!sb) return [];

  let q = sb
    .from('documents')
    .select('*')
    .order('uploaded_at', { ascending: false });

  if (status) q = (q as any).eq('status', status);

  const { data, error } = await q;
  if (error) {
    console.error('[Supabase] getDocuments error:', error.message);
    return [];
  }
  return (data ?? []) as SbDocument[];
}

export async function sbRemoveDocument(documentId: string): Promise<boolean> {
  const sb = getSupabaseClient();
  if (!sb) return false;

  const { error } = await sb
    .from('documents')
    .delete()
    .eq('document_id', documentId);

  if (error) {
    console.error('[Supabase] removeDocument error:', error.message);
    return false;
  }
  return true;
}

export async function sbDocumentExists(documentId: string): Promise<boolean> {
  const sb = getSupabaseClient();
  if (!sb) return false;

  const { data } = await sb
    .from('documents')
    .select('document_id')
    .eq('document_id', documentId)
    .limit(1);

  return !!(data && data.length > 0);
}

export async function sbCountDocuments(): Promise<number> {
  const sb = getSupabaseClient();
  if (!sb) return 0;

  const { count, error } = await sb
    .from('documents')
    .select('document_id', { count: 'exact', head: true });

  if (error) return 0;
  return count ?? 0;
}

// ─── Chunks ───────────────────────────────────────────────────────────────────

export async function sbInsertChunks(
  chunks: Array<{
    chunk_id: string;
    document_id: string;
    document_name: string;
    page: number;
    chunk_index: number;
    text: string;
    embedding: number[];
  }>
): Promise<boolean> {
  const sb = getSupabaseClient();
  if (!sb || chunks.length === 0) return false;

  const BATCH = 5;
  for (let i = 0; i < chunks.length; i += BATCH) {
    const batch = chunks.slice(i, i + BATCH).map(c => ({
      // chunk_id is auto-generated by Supabase (uuid default)
      document_id: c.document_id,
      document_name: c.document_name,
      page_number: c.page,
      chunk_index: c.chunk_index,
      content: c.text,
      embedding: c.embedding,
    }));

    const { error } = await sb.from('document_chunks').insert(batch);
    if (error) {
      console.error(`[Supabase] insertChunks batch error:`, error.message);
    }
  }
  return true;
}

export async function sbGetDocumentContent(documentId: string): Promise<string> {
  const sb = getSupabaseClient();
  if (!sb) return '';

  const { data, error } = await sb
    .from('document_chunks')
    .select('content, chunk_index')
    .eq('document_id', documentId)
    .order('chunk_index', { ascending: true });

  if (error || !data) return '';
  return data.map((r: any) => r.content).join('\n');
}

// ─── Vector Search ─────────────────────────────────────────────────────────────

export async function sbSearchChunks(
  queryEmbedding: number[],
  topK = 8,
  scoreThreshold = 0.25
): Promise<{ chunk: SbChunk; score: number }[]> {
  const sb = getSupabaseClient();
  if (!sb) return [];

  const { data, error } = await sb.rpc('search_chunks', {
    query_embedding: queryEmbedding,
    match_count: topK,
    score_threshold: scoreThreshold,
  });

  if (error) {
    console.error('[Supabase] search_chunks error:', error.message);
    return [];
  }

  return (data ?? []).map((row: any) => ({
    chunk: {
      chunk_id: row.chunk_id ?? row.id,
      document_id: row.document_id,
      document_name: row.document_name,
      page: row.page_number ?? 1,
      chunk_index: row.chunk_index ?? 0,
      text: row.content,
    },
    score: row.score ?? row.similarity ?? 0,
  }));
}

// ─── Query History ─────────────────────────────────────────────────────────────

export async function sbLogQuery(q: {
  query_id: string;
  question: string;
  answer: string;
  latency_ms: number;
  user: string;
  timestamp: string;
  sources: any[];
}): Promise<void> {
  const sb = getSupabaseClient();
  if (!sb) return;

  await sb.from('query_history').insert({
    question: q.question,
    answer: q.answer,
    latency_ms: q.latency_ms,
    "user": q.user,
    "timestamp": q.timestamp,
    sources: q.sources,
  }).then(({ error }) => {
    if (error) console.error('[Supabase] logQuery error:', error.message);
  });
}

// ─── Authentication ─────────────────────────────────────────────────────────────

export async function sbGetUserByEmail(email: string) {
  const sb = getSupabaseClient();
  if (!sb) return null;

  const { data, error } = await sb
    .from('users')
    .select('*')
    .eq('email', email)
    .single();

  if (error || !data) {
    return null;
  }
  return data;
}

export async function sbCreateUser(email: string, passwordHash: string, name: string, role: string) {
  const sb = getSupabaseClient();
  if (!sb) return null;

  const { data, error } = await sb
    .from('users')
    .insert([{ email, password_hash: passwordHash, name, role }])
    .select('*')
    .single();

  if (error || !data) {
    console.error('[Supabase] sbCreateUser error:', error?.message);
    return null;
  }
  return data;
}

// ─── Storage ─────────────────────────────────────────────────────────────────

export async function sbGetSignedUrl(filePath: string, expiresInSeconds = 300): Promise<string | null> {
  const sb = getSupabaseClient();
  if (!sb) return null;

  const bucket = process.env.SUPABASE_STORAGE_BUCKET || 'documents';
  try {
    const { data, error } = await sb.storage.from(bucket).createSignedUrl(filePath, expiresInSeconds);
    if (error || !data) {
      console.warn(`[Supabase Storage] createSignedUrl warning (${filePath}):`, error?.message);
      return null;
    }
    return data.signedUrl;
  } catch (e: any) {
    console.warn(`[Supabase Storage] Exception creating signed url:`, e?.message);
    return null;
  }
}

